### ISSUE TITLE
missing CN separators （）【】{}《》

### ISSUE THREAD

**Issue by tjx666** [jackiotyu/vscode-word-separator#2]
this sis my configuration:

```json
{
    "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:：'\",.<>/?，。‘’“”；（）【】{}《》「」",
}
```

**Comment by jackiotyu** [comment]
![image](https://user-images.githubusercontent.com/31788042/218289496-4e7f0450-eb13-4545-82ea-41fb6f0eccf6.png)
![image](https://user-images.githubusercontent.com/31788042/218289497-ead7a110-242c-4f0d-ba0b-50fc3fb776e9.png)
Ok, you can add those separators by edit item. I will add builtin later.
